# VitalFlow-Radar: Google App Engine Configuration
# Alternative deployment option using App Engine Flexible
#
# Deploy: gcloud app deploy app.yaml

runtime: custom
env: flex

# Resources
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

# Automatic scaling
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6

# Health checks
liveness_check:
  path: "/api/health"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 3
  success_threshold: 1
  initial_delay_sec: 120

readiness_check:
  path: "/api/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

# Environment variables
env_variables:
  VITALFLOW_ENV: "production"
  VITALFLOW_DB: "/app/data/vitalflow.db"

# Network settings
network:
  session_affinity: false
