# VitalFlow-Radar: Google Cloud Build Configuration
# Builds and deploys to Cloud Run
#
# Deployment: gcloud builds submit --config cloudbuild.yaml

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/vitalflow-radar:${_SHORT_SHA}'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/vitalflow-radar:latest'
      - '-f'
      - 'Dockerfile.cloudrun'
      - '.'

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/vitalflow-radar:${_SHORT_SHA}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/vitalflow-radar:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'vitalflow-radar'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/vitalflow-radar:${_SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'VITALFLOW_ENV=production,VITALFLOW_DB=/app/data/vitalflow.db'

# Store images in Container Registry
images:
  - 'gcr.io/${PROJECT_ID}/vitalflow-radar:${_SHORT_SHA}'
  - 'gcr.io/${PROJECT_ID}/vitalflow-radar:latest'

# Substitution variables (can be overridden)
substitutions:
  _REGION: us-central1
  _SHORT_SHA: latest

# Build timeout (15 minutes)
timeout: '900s'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
